### ISSUE TITLE
LInk is wrong!

### ISSUE THREAD

**Issue by prljav** [JagTheFriend/Complex-API#1]
in readme.md u have still old pip pls fix it.

I know isnt that much of issue but still.

**Comment by prljav** [comment]
I think it will work without new link but i suggest u to make it

**Comment by JagTheFriend** [comment]
Which link are you talking about ?
(there are 15 links in total)

**Comment by prljav** [comment]
![image](https://user-images.githubusercontent.com/74116121/111907672-ada4a080-8a56-11eb-838e-6d9c3d9798b1.png)

**Comment by JagTheFriend** [comment]
The link (<a href="https://pypi.org/project/Complex-API/">this module (`pip install Complex-API`)</a>) take you to pypi
